### PR TITLE
Reformat FaceID [GG-81]

### PR DESCRIPTION
**Pull request by kemptonk**
Restructured faceID.py, clean-up code, and add comments.

### CODE REVIEW

**Comment by mraynor** [comment]
👍

**Comment by lb-cake** [comment]
Merge Conflicts due to the last merge. A quick rebase should solve this. (sorry 😅)

**Review by orndorffc — APPROVED** [review]
Looks good!

**Review by lb-cake — CHANGES_REQUESTED** [review]
Let's talk via Slack or IRL before merge.

**Review by lb-cake — APPROVED** [review]

**Pull request merged**
